# Generated by Django 4.0.5 on 2022-07-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_cursoApp', '0002_alter_evento_info_alter_evento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
    ]
