# Generated by Django 4.0.5 on 2022-07-15 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_cursoApp', '0005_comentario_remove_avatar_id_alter_avatar_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='comentario',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
